// cost is in Watts and entries must be sorted in increasing cost
// cost represents 1 hour's worth of embodied energy over the lifetime of the item
challengeData = [
  { cost:1.432,  what:'a roll of aluminum foil' },
  { cost:1.773,  what:'a golf ball' },
  { cost:2.563,  what:'a daily newspaper' },
  { cost:2.659,  what:'a stainless steel pan' },
  { cost:2.883,  what:'a standard office chair' },
  { cost:2.915,  what:'a charcoal BBQ' },
  { cost:3.683,  what:'a pair of sneakers' },
  { cost:3.943,  what:'a toothbrush' },
  { cost:4.818,  what:'a microwave oven' },
  { cost:5.122,  what:'a skateboard' },
  { cost:5.503,  what:'a tea bag' },
  { cost:6.796,  what:'a bottle of shampoo' },
  { cost:8.404,  what:'a window AC unit' },
  { cost:9.559,  what:'a monthly magazine' },
  { cost:9.894,  what:'a racing bicycle' },
  { cost:10.722, what:'an electric stove' },
  { cost:11.975, what:'a mini refrigerator' },
  { cost:12.517, what:'an Apple iPhone' },
  { cost:12.688, what:'a Motorola droid' },
  { cost:25.33,  what:'a paper cup' },
  { cost:25.519, what:'a roll of toilet paper' },
  { cost:26.53,  what:'a point and shoot camera' },
  { cost:29.572, what:'a baby car seat' },
  { cost:31.91,  what:'a futon mattress' },
  { cost:33.336, what:'a snowboard' },
  { cost:40.871, what:'a grand piano' },
  { cost:42.561, what:'a baby stroller' },
  { cost:54.8,   what:'a conference name badge' },
  { cost:55.737, what:'an Xbox 360' },
  { cost:64.569, what:'a Christmas tree' },
  { cost:65.927, what:'a disposable plastic bottle' },
  { cost:67.279, what:'a laptop charger' },
  { cost:93.415, what:'a gallon of milk' },
  { cost:104.21, what:'a Blu-ray player' },
  { cost:165.994,what:'a 42" flat panel LCD TV' },
  { cost:197.945,what:'a central AC unit' },
  { cost:239.72, what:'a Toyota prius' },
  { cost:236.19, what:'a jet ski' },
  { cost:918.014,what:'a rooftop solar system' },
  { cost:1954,   what:'a 45-ft sailboat' }
];
